[package]
name = "crash-child"
version = "0.1.0"
edition = "2021"
[workspace]
[lib]
crate-type = ["cdylib"]
[dependencies]
packr-guest = { version = "0.24", features = ["derive"] }
packr-abi = { version = "0.24", default-features = false }
theater-guest = { git = "https://github.com/colinrozzi/theater", rev = "0b60fdb6a018c02c7af2e5b72481bc20956b26d5" }
[profile.release]
opt-level = "s"
lto = true
