[package]
name = "crash-child"
version = "0.1.0"
edition = "2021"
[workspace]
[lib]
crate-type = ["cdylib"]
[dependencies]
packr-guest = { version = "0.24.1", features = ["derive"] }
packr-abi = { version = "0.24.1", default-features = false }
theater-guest = { git = "https://github.com/colinrozzi/theater", rev = "82cc6217fcd5d4288e4c7aea5602197630e7dde3" }
[profile.release]
opt-level = "s"
lto = true
